### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by bvanbens** [avholloway/cisco-phone-controller#1]
Awesome plug-in,  Thanks for sharing with the community.
Was just testing today for a few minutes.  Most items worked but the **Settings button** was not doing anything when I tested on 2 phones.  8845 and 9971.
CUCM 12.5 SU2  / FF 79.0
![8845-screenCap](https://user-images.githubusercontent.com/18484517/90560363-98842e00-e164-11ea-9957-a64ec542fcee.png)

**Comment by avholloway** [comment]
Here is documentation regarding which keys are available on which phone models:
https://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cuipph/all_models/xsi/9-1-1/CUIP_BK_P82B3B16_00_phones-services-application-development-notes/CUIP_BK_P82B3B16_00_phones-services-application-development-notes_chapter_0101.html#CUIP_RF_U95C2769_00

Snippet from the documentation on the 9971:
**Note** Key:Info, Key:Services, Key:Directories, Key:Settings, Key:AppMenu, and Key:Hold are not supported by Cisco Unified IP Phones 8961, 9951, and 9971.

As far as I can tell, it should work on the 8845, and infact, it should work on my own 8851, but documentation has been known to be wrong too.  If your testing shows that it's not working, then I would recommend trying the Applications button instead.  They tend to do the same thing across models.  For example, when I press Applications on my 8851, it brings up the same screen as if I pressed the gear icon for settings physical button.

I hope that helps.

**Comment by bvanbens** [comment]
The applications button works just as you describe.  Didn't think to try it.
Still loving the app !
