### ISSUE TITLE
Not Able to see the screen of the phone.

### ISSUE THREAD

**Issue by Chikkis** [avholloway/cisco-phone-controller#3]
Hi Anthony,

I am having issue the view the phone screenshot. i tried using the screen shot url but is giving

<CiscoIPPhoneError Number="4" />

please help.

**Comment by avholloway** [comment]
Hi Chikkis,

I'm not sure I understand the problem you are facing, as it seems your sentence tapered off there at the end.  Did you meant to share an Error Message or screenshot?

If you are trying the built-in /CGI/Screenshot url and it's not working, then this is not an add-on problem, rather a phone/cucm problem.

Try checking that your phone's Web Access setting is enabled in CUCM on the device page, and that you can navigate to the IP address of the phone in your browser.  If that works, then make sure you assigned the phone as a Controlled Device to either an Application User or an End User in CUCM.  One last double check if it's still not working, is that your Authentication URL is the standard one, and was not modified, like can be the case when integrating with third party paging systems, who need to control all phones easily.

**Comment by avholloway** [comment]
No response.
