### ISSUE TITLE
Not working if phone locale isnt english

### ISSUE THREAD

**Issue by TaNg73** [avholloway/cisco-phone-controller#4]
Hi,
I have a mix of phones using different locales.
This works well with english locale but not on french locale ("Control me" does not appear)
Is there a way of making this work on phones with locale other than english ?
I would not mind if the controls were always in english

Thanks

**Comment by avholloway** [comment]
Hi there! I'd be happy to update the app to work with the French locale.  Could you do me a favor and right click the "Device Information" heading at the top of the page in white and select Inspect Element, and then copy the <font> tag with the heading inside; include the closing </font> tag too!  Once I have that, I should be able to modify the code to detect French phones now.  Thank you!

**Comment by TaNg73** [comment]
Hi,

Here is the info you requested....I think...
I am a newbie so if this aint what you need, please let me know

Thanks

Simon

<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><title>Cisco Systems, Inc.</title>
</head><body vlink="#FFFFFF" text="#003031" link="#FFFFFF" bgcolor="#FFFFFF" alink="#FFFFFF"><table width="100%" height="100%" cellspacing="0" cellpadding="0" bordercolor="#003031" border="1"><tbody><tr>
<td width="200" height="100" align="center"><a href="http://www.cisco.com"><img src="/FS/Logo.png"></a></td><td height="50" bgcolor="#003031"><p align="center"><b><font size="6" color="#FFFFFF">Info. périphérique</font></b></p><p align="center"><b><font size="4" color="#FFFFFF">Cisco Unified IP Phone CP-7945G ( SEP8CB64F56AA69 )</font></b></p></td>
</tr>
<tr><td width="200" valign="top" bgcolor="#003031" align="center"><table cellspacing="10" cellpadding="0" border="0"><tbody><tr>
<td><a href="/CGI/Java/Serviceability?adapter=device.statistics.device">Info. périphérique</a></td></tr>
<tr>
<td><a href="/CGI/Java/Serviceability?adapter=device.statistics.configuration">Configuration réseau</a></td></tr>
<tr><td><b><font color="#FFFFFF">Statistiques réseau</font></b></td></tr><tr>
<td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.ethernet">Informations Ethernet</a></td>
</tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.port.access">Accès</a></td></tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.port.network">Réseau</a></td></tr><tr><td><b><font color="#FFFFFF">Journaux des périphériques</font></b></td></tr><tr>
<td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.consolelog">Journaux de la console</a></td></tr><tr>
<td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.coredumps">Vidages mémoire</a></td></tr><tr>
<td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.settings.status.messages">Messages d'état</a></td></tr>
<tr>
<td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.trace.display.alarm">Affichage debug</a></td></tr>
<tr><td><b><font color="#FFFFFF">Statistiques de streaming</font></b></td></tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.streaming.0">Flux 1 </a></td></tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.streaming.1">Flux 2 </a></td></tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.streaming.2">Flux 3 </a></td></tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.streaming.3">Flux 4 </a></td></tr><tr><td>&nbsp;&nbsp;&nbsp;<a href="/CGI/Java/Serviceability?adapter=device.statistics.streaming.4">Flux 5 </a></td></tr></tbody></table>
</td>
<td valign="top"><div align="center">
<table cellspacing="10" cellpadding="0" border="0"><tbody><tr><td><b> Adresse MAC</b></td><td width="20"></td><td><b>8CB64F56AA69</b></td></tr><tr><td><b> Nom hôte</b></td><td width="20"></td><td><b>SEP8CB64F56AA69</b></td></tr><tr><td><b> Numéro de téléphone</b></td><td width="20"></td><td><b>4105682</b></td></tr><tr><td><b> ID charg. app.</b></td><td width="20"></td><td><b>jar45sip.9-4-2SR4-3.sbn</b></td></tr><tr><td><b> ID image démarrage</b></td><td width="20"></td><td><b>tnp45.8-3-1-21a.bin</b></td></tr><tr><td><b> Version</b></td><td width="20"></td><td><b>*SIP45.9-4-2SR4-3S*</b></td></tr><tr><td><b> Version du matériel</b></td><td width="20"></td><td><b>12.0</b></td></tr><tr><td><b> Numéro de série</b></td><td width="20"></td><td><b>FCH14528L1W</b></td></tr><tr><td><b> Numéro du modèle</b></td><td width="20"></td><td><b>CP-7945G</b></td></tr><tr><td><b> Message en attente</b></td><td width="20"></td><td><b>Non</b></td></tr><tr><td><b> UDI</b></td><td width="20"></td><td><b>phone</b></td></tr><tr><td><b> </b></td><td width="20"></td><td><b>Cisco Unified IP Phone 7945G, Global, Gig Ethernet, Color</b></td></tr><tr><td><b> </b></td><td width="20"></td><td><b>CP-7945G</b></td></tr><tr><td><b> </b></td><td width="20"></td><td><b>V09</b></td></tr><tr><td><b> </b></td><td width="20"></td><td><b>FCH14528L1W</b></td></tr><tr><td><b> Hr</b></td><td width="20"></td><td><b>08:21:44</b></td></tr><tr><td><b> Fuseau horaire</b></td><td width="20"></td><td><b>America/New_York</b></td></tr><tr><td><b> Date</b></td><td width="20"></td><td><b>15/12/20</b></td></tr><tr><td><b> Mémoire libre du système</b></td><td width="20"></td><td><b>2028192</b></td></tr><tr><td><b> Mémoire libre du Java heap</b></td><td width="20"></td><td><b>905336</b></td></tr><tr><td><b> Mémoire libre du Java pool</b></td><td width="20"></td><td><b>553656</b></td></tr><tr><td><b> Mode FIPS activé</b></td><td width="20"></td><td><b>Non</b></td></tr></tbody></table></div></td></tr></tbody></table></body>

**Comment by avholloway** [comment]
Ok, thank you.  I think it's this portion that I needed:
`<font size="6" color="#FFFFFF">Info. périphérique</font>`
In the English Locale it says Device information, and in French it looks like it might be Peripheral information (roughly translated in google translate).
I'll see what I can do from here.  Thanks again.

**Comment by avholloway** [comment]
I have a new version being reviewed by Mozilla today.  I'll post back once it's approved.

**Comment by avholloway** [comment]
It should now support French locale in v1.6.  Please update your addon in FF and let me know.

**Comment by TaNg73** [comment]
Hi,

Good job !
I tested on the different models we have on our CM and It seems to be working on most of them.

For the models other that the 7937 that aren't working, I see that Cisco didn't used the same string to identify the page title (see table below)
Hope this info can help you.

In the table below, the "?" indicate that I couldn't test because I didn't have this language/model combination connected to our CM.


English
French
"Device Information" translation used
7911
?
Yes
 "Info. périphérique"
7937
No
No
 "Info. périphérique"
7941
Yes
Yes
 "Info. périphérique"
7941G-GE
Yes
Yes
 "Info. périphérique"
7942
Yes
Yes
 "Info. périphérique"
7945
Yes
Yes
 "Info. périphérique"
7961
Yes
Yes
 "Info. périphérique"
7961G-GE
Yes
?
 "Info. périphérique"
7962
Yes
Yes
 "Info. périphérique"




7841
Yes
No
"Info. sur le périph."
8831
Yes
No
"Information périphérique"
8861
Yes
No
"Renseignements sur le périphérique"





Thanks !

**Comment by TaNg73** [comment]
Hi,

Good job ! 
I tested on the different models we have on our CM and It seems to be working on most of them.

For the models other that the 7937 that aren’t working, I see that Cisco didn’t used the same string to identify the page title (see table below)
Hope this info can help you.

In the table below, the “?” indicate that I couldn’t test because I didn’t have this language/model combination connected to our CM.
![image](https://user-images.githubusercontent.com/76052297/102700365-c06ec580-421a-11eb-82f5-22e82281eed6.png)

Thanks

**Comment by avholloway** [comment]
That is very helpful work you've done, and now that I see how inconsistent Cisco has been in this regard, it makes me think that I should find a different method which could work on more models and more locales.  For example, stop checking for the header text itself, and instead look for the font tag with the white color, or something like that.  I'll need to think about that a little more, but in the mean time, I can use your translation table to add in the 7841, 8831, and 8861 text in a v1.7 update, within just a few minutes.  I'll reply again, once that has been uploaded and approved by Mozilla.

**Comment by avholloway** [comment]
Looks like 1.7 has just been approved and released.  Please update and let me know!

**Comment by avholloway** [comment]
Also, the 7937 is just not a model I can support right now, so I only targeted your last three french models.

**Comment by TaNg73** [comment]
I can connect to 7841, 8831, 8861 phones now.
I agree you should use something more constant. The color is a great idea, I am pretty sure the colors are the same for all the languages.

**Comment by avholloway** [comment]
I will be looking into that.  Cheers!
